name: Deploy SportsHall API Server
on:
  push:
    branches:
      - main
    paths:
      - "**/*"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

jobs:
  deploy:
    name: Deploy zip files to AWS lambda
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: "."
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: chmod +x ./build_lambda.sh && ./build_lambda.sh api_server_node

      - name: Upload to S3
        run: aws s3 cp lambda_zip/api_server_node.zip s3://codezip-molip/

      - name: Deploy
        run: aws lambda update-function-code --function-name sportshall --s3-bucket codezip-sportshall --s3-key api_server_node.zip
