DROP TABLE IF EXISTS Molip_Rankings
CREATE TABLE Molip_Rankings (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user_id VARCHAR(255) NOT NULL,
    challenge_id INT NOT NULL,
    dt VARCHAR(20) NOT NULL,
    rank INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    status VARCHAR(15) DEFAULT 'activate'
);